Repository ComicScrip/lyon-react-mars22-p2g5, pull requests merged in 2022-04, with the labels that each got.

#42 Navigation
  package-lock.json
  package.json
  src/components/Footer.js
  src/components/Footer.jsx
  src/components/Header.css
  src/components/Header.jsx
  src/setupTests.js
  src/styles/footer.css
Labels: Ready for validation, Ready for prod

#45 creation of the categorie page (temporary) with a category button to …
  src/assets/Star.jpeg
  src/components/CategorieTempo.jsx
  src/components/Header.jsx
  src/components/Main.js
  src/styles/QuizPage.css
  src/styles/categorieTempo.css
Labels: Ready for validation, Ready for prod

#53 Result
  src/App.js
  src/assets/check2.png
  src/assets/wrong2.png
  src/components/Home.jsx
  src/components/Main.js
  src/components/ResultDummy.jsx
  src/components/ResultPage.jsx
  src/styles/ResultPage.css
Labels: Ready for validation

#55 Timer bar
  src/components/QuizAPI.jsx
  src/components/ResultPage.jsx
  src/components/Temporaire.jsx
  src/index.js
  src/styles/ProgressBar.css
  src/styles/QuizPage.css
  src/styles/footer.css
Labels: Ready for prod
